# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/daniel/Documents/Research/software/SCS/scs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/daniel/Documents/Research/software/SCS/scs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"runtime\" \"scs\" \"shlib\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel/Documents/Research/software/SCS/scs/CMakeFiles /home/daniel/Documents/Research/software/SCS/scs//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel/Documents/Research/software/SCS/scs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named scsdir

# Build rule for target.
scsdir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scsdir
.PHONY : scsdir

# fast build rule for target.
scsdir/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/build
.PHONY : scsdir/fast

#=============================================================================
# Target rules for targets named scsindir

# Build rule for target.
scsindir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scsindir
.PHONY : scsindir

# fast build rule for target.
scsindir/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/build
.PHONY : scsindir/fast

#=============================================================================
# Target rules for targets named scsmkl

# Build rule for target.
scsmkl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scsmkl
.PHONY : scsmkl

# fast build rule for target.
scsmkl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/build
.PHONY : scsmkl/fast

linsys/cpu/direct/private.o: linsys/cpu/direct/private.c.o
.PHONY : linsys/cpu/direct/private.o

# target to build an object file
linsys/cpu/direct/private.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/cpu/direct/private.c.o
.PHONY : linsys/cpu/direct/private.c.o

linsys/cpu/direct/private.i: linsys/cpu/direct/private.c.i
.PHONY : linsys/cpu/direct/private.i

# target to preprocess a source file
linsys/cpu/direct/private.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/cpu/direct/private.c.i
.PHONY : linsys/cpu/direct/private.c.i

linsys/cpu/direct/private.s: linsys/cpu/direct/private.c.s
.PHONY : linsys/cpu/direct/private.s

# target to generate assembly for a file
linsys/cpu/direct/private.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/cpu/direct/private.c.s
.PHONY : linsys/cpu/direct/private.c.s

linsys/cpu/indirect/private.o: linsys/cpu/indirect/private.c.o
.PHONY : linsys/cpu/indirect/private.o

# target to build an object file
linsys/cpu/indirect/private.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/linsys/cpu/indirect/private.c.o
.PHONY : linsys/cpu/indirect/private.c.o

linsys/cpu/indirect/private.i: linsys/cpu/indirect/private.c.i
.PHONY : linsys/cpu/indirect/private.i

# target to preprocess a source file
linsys/cpu/indirect/private.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/linsys/cpu/indirect/private.c.i
.PHONY : linsys/cpu/indirect/private.c.i

linsys/cpu/indirect/private.s: linsys/cpu/indirect/private.c.s
.PHONY : linsys/cpu/indirect/private.s

# target to generate assembly for a file
linsys/cpu/indirect/private.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/linsys/cpu/indirect/private.c.s
.PHONY : linsys/cpu/indirect/private.c.s

linsys/csparse.o: linsys/csparse.c.o
.PHONY : linsys/csparse.o

# target to build an object file
linsys/csparse.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/csparse.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/linsys/csparse.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/linsys/csparse.c.o
.PHONY : linsys/csparse.c.o

linsys/csparse.i: linsys/csparse.c.i
.PHONY : linsys/csparse.i

# target to preprocess a source file
linsys/csparse.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/csparse.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/linsys/csparse.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/linsys/csparse.c.i
.PHONY : linsys/csparse.c.i

linsys/csparse.s: linsys/csparse.c.s
.PHONY : linsys/csparse.s

# target to generate assembly for a file
linsys/csparse.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/csparse.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/linsys/csparse.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/linsys/csparse.c.s
.PHONY : linsys/csparse.c.s

linsys/external/amd/SuiteSparse_config.o: linsys/external/amd/SuiteSparse_config.c.o
.PHONY : linsys/external/amd/SuiteSparse_config.o

# target to build an object file
linsys/external/amd/SuiteSparse_config.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/SuiteSparse_config.c.o
.PHONY : linsys/external/amd/SuiteSparse_config.c.o

linsys/external/amd/SuiteSparse_config.i: linsys/external/amd/SuiteSparse_config.c.i
.PHONY : linsys/external/amd/SuiteSparse_config.i

# target to preprocess a source file
linsys/external/amd/SuiteSparse_config.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/SuiteSparse_config.c.i
.PHONY : linsys/external/amd/SuiteSparse_config.c.i

linsys/external/amd/SuiteSparse_config.s: linsys/external/amd/SuiteSparse_config.c.s
.PHONY : linsys/external/amd/SuiteSparse_config.s

# target to generate assembly for a file
linsys/external/amd/SuiteSparse_config.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/SuiteSparse_config.c.s
.PHONY : linsys/external/amd/SuiteSparse_config.c.s

linsys/external/amd/amd_1.o: linsys/external/amd/amd_1.c.o
.PHONY : linsys/external/amd/amd_1.o

# target to build an object file
linsys/external/amd/amd_1.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_1.c.o
.PHONY : linsys/external/amd/amd_1.c.o

linsys/external/amd/amd_1.i: linsys/external/amd/amd_1.c.i
.PHONY : linsys/external/amd/amd_1.i

# target to preprocess a source file
linsys/external/amd/amd_1.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_1.c.i
.PHONY : linsys/external/amd/amd_1.c.i

linsys/external/amd/amd_1.s: linsys/external/amd/amd_1.c.s
.PHONY : linsys/external/amd/amd_1.s

# target to generate assembly for a file
linsys/external/amd/amd_1.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_1.c.s
.PHONY : linsys/external/amd/amd_1.c.s

linsys/external/amd/amd_2.o: linsys/external/amd/amd_2.c.o
.PHONY : linsys/external/amd/amd_2.o

# target to build an object file
linsys/external/amd/amd_2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_2.c.o
.PHONY : linsys/external/amd/amd_2.c.o

linsys/external/amd/amd_2.i: linsys/external/amd/amd_2.c.i
.PHONY : linsys/external/amd/amd_2.i

# target to preprocess a source file
linsys/external/amd/amd_2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_2.c.i
.PHONY : linsys/external/amd/amd_2.c.i

linsys/external/amd/amd_2.s: linsys/external/amd/amd_2.c.s
.PHONY : linsys/external/amd/amd_2.s

# target to generate assembly for a file
linsys/external/amd/amd_2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_2.c.s
.PHONY : linsys/external/amd/amd_2.c.s

linsys/external/amd/amd_aat.o: linsys/external/amd/amd_aat.c.o
.PHONY : linsys/external/amd/amd_aat.o

# target to build an object file
linsys/external/amd/amd_aat.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_aat.c.o
.PHONY : linsys/external/amd/amd_aat.c.o

linsys/external/amd/amd_aat.i: linsys/external/amd/amd_aat.c.i
.PHONY : linsys/external/amd/amd_aat.i

# target to preprocess a source file
linsys/external/amd/amd_aat.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_aat.c.i
.PHONY : linsys/external/amd/amd_aat.c.i

linsys/external/amd/amd_aat.s: linsys/external/amd/amd_aat.c.s
.PHONY : linsys/external/amd/amd_aat.s

# target to generate assembly for a file
linsys/external/amd/amd_aat.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_aat.c.s
.PHONY : linsys/external/amd/amd_aat.c.s

linsys/external/amd/amd_control.o: linsys/external/amd/amd_control.c.o
.PHONY : linsys/external/amd/amd_control.o

# target to build an object file
linsys/external/amd/amd_control.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_control.c.o
.PHONY : linsys/external/amd/amd_control.c.o

linsys/external/amd/amd_control.i: linsys/external/amd/amd_control.c.i
.PHONY : linsys/external/amd/amd_control.i

# target to preprocess a source file
linsys/external/amd/amd_control.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_control.c.i
.PHONY : linsys/external/amd/amd_control.c.i

linsys/external/amd/amd_control.s: linsys/external/amd/amd_control.c.s
.PHONY : linsys/external/amd/amd_control.s

# target to generate assembly for a file
linsys/external/amd/amd_control.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_control.c.s
.PHONY : linsys/external/amd/amd_control.c.s

linsys/external/amd/amd_defaults.o: linsys/external/amd/amd_defaults.c.o
.PHONY : linsys/external/amd/amd_defaults.o

# target to build an object file
linsys/external/amd/amd_defaults.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_defaults.c.o
.PHONY : linsys/external/amd/amd_defaults.c.o

linsys/external/amd/amd_defaults.i: linsys/external/amd/amd_defaults.c.i
.PHONY : linsys/external/amd/amd_defaults.i

# target to preprocess a source file
linsys/external/amd/amd_defaults.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_defaults.c.i
.PHONY : linsys/external/amd/amd_defaults.c.i

linsys/external/amd/amd_defaults.s: linsys/external/amd/amd_defaults.c.s
.PHONY : linsys/external/amd/amd_defaults.s

# target to generate assembly for a file
linsys/external/amd/amd_defaults.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_defaults.c.s
.PHONY : linsys/external/amd/amd_defaults.c.s

linsys/external/amd/amd_dump.o: linsys/external/amd/amd_dump.c.o
.PHONY : linsys/external/amd/amd_dump.o

# target to build an object file
linsys/external/amd/amd_dump.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_dump.c.o
.PHONY : linsys/external/amd/amd_dump.c.o

linsys/external/amd/amd_dump.i: linsys/external/amd/amd_dump.c.i
.PHONY : linsys/external/amd/amd_dump.i

# target to preprocess a source file
linsys/external/amd/amd_dump.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_dump.c.i
.PHONY : linsys/external/amd/amd_dump.c.i

linsys/external/amd/amd_dump.s: linsys/external/amd/amd_dump.c.s
.PHONY : linsys/external/amd/amd_dump.s

# target to generate assembly for a file
linsys/external/amd/amd_dump.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_dump.c.s
.PHONY : linsys/external/amd/amd_dump.c.s

linsys/external/amd/amd_global.o: linsys/external/amd/amd_global.c.o
.PHONY : linsys/external/amd/amd_global.o

# target to build an object file
linsys/external/amd/amd_global.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_global.c.o
.PHONY : linsys/external/amd/amd_global.c.o

linsys/external/amd/amd_global.i: linsys/external/amd/amd_global.c.i
.PHONY : linsys/external/amd/amd_global.i

# target to preprocess a source file
linsys/external/amd/amd_global.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_global.c.i
.PHONY : linsys/external/amd/amd_global.c.i

linsys/external/amd/amd_global.s: linsys/external/amd/amd_global.c.s
.PHONY : linsys/external/amd/amd_global.s

# target to generate assembly for a file
linsys/external/amd/amd_global.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_global.c.s
.PHONY : linsys/external/amd/amd_global.c.s

linsys/external/amd/amd_info.o: linsys/external/amd/amd_info.c.o
.PHONY : linsys/external/amd/amd_info.o

# target to build an object file
linsys/external/amd/amd_info.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_info.c.o
.PHONY : linsys/external/amd/amd_info.c.o

linsys/external/amd/amd_info.i: linsys/external/amd/amd_info.c.i
.PHONY : linsys/external/amd/amd_info.i

# target to preprocess a source file
linsys/external/amd/amd_info.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_info.c.i
.PHONY : linsys/external/amd/amd_info.c.i

linsys/external/amd/amd_info.s: linsys/external/amd/amd_info.c.s
.PHONY : linsys/external/amd/amd_info.s

# target to generate assembly for a file
linsys/external/amd/amd_info.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_info.c.s
.PHONY : linsys/external/amd/amd_info.c.s

linsys/external/amd/amd_order.o: linsys/external/amd/amd_order.c.o
.PHONY : linsys/external/amd/amd_order.o

# target to build an object file
linsys/external/amd/amd_order.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_order.c.o
.PHONY : linsys/external/amd/amd_order.c.o

linsys/external/amd/amd_order.i: linsys/external/amd/amd_order.c.i
.PHONY : linsys/external/amd/amd_order.i

# target to preprocess a source file
linsys/external/amd/amd_order.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_order.c.i
.PHONY : linsys/external/amd/amd_order.c.i

linsys/external/amd/amd_order.s: linsys/external/amd/amd_order.c.s
.PHONY : linsys/external/amd/amd_order.s

# target to generate assembly for a file
linsys/external/amd/amd_order.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_order.c.s
.PHONY : linsys/external/amd/amd_order.c.s

linsys/external/amd/amd_post_tree.o: linsys/external/amd/amd_post_tree.c.o
.PHONY : linsys/external/amd/amd_post_tree.o

# target to build an object file
linsys/external/amd/amd_post_tree.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_post_tree.c.o
.PHONY : linsys/external/amd/amd_post_tree.c.o

linsys/external/amd/amd_post_tree.i: linsys/external/amd/amd_post_tree.c.i
.PHONY : linsys/external/amd/amd_post_tree.i

# target to preprocess a source file
linsys/external/amd/amd_post_tree.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_post_tree.c.i
.PHONY : linsys/external/amd/amd_post_tree.c.i

linsys/external/amd/amd_post_tree.s: linsys/external/amd/amd_post_tree.c.s
.PHONY : linsys/external/amd/amd_post_tree.s

# target to generate assembly for a file
linsys/external/amd/amd_post_tree.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_post_tree.c.s
.PHONY : linsys/external/amd/amd_post_tree.c.s

linsys/external/amd/amd_postorder.o: linsys/external/amd/amd_postorder.c.o
.PHONY : linsys/external/amd/amd_postorder.o

# target to build an object file
linsys/external/amd/amd_postorder.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_postorder.c.o
.PHONY : linsys/external/amd/amd_postorder.c.o

linsys/external/amd/amd_postorder.i: linsys/external/amd/amd_postorder.c.i
.PHONY : linsys/external/amd/amd_postorder.i

# target to preprocess a source file
linsys/external/amd/amd_postorder.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_postorder.c.i
.PHONY : linsys/external/amd/amd_postorder.c.i

linsys/external/amd/amd_postorder.s: linsys/external/amd/amd_postorder.c.s
.PHONY : linsys/external/amd/amd_postorder.s

# target to generate assembly for a file
linsys/external/amd/amd_postorder.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_postorder.c.s
.PHONY : linsys/external/amd/amd_postorder.c.s

linsys/external/amd/amd_preprocess.o: linsys/external/amd/amd_preprocess.c.o
.PHONY : linsys/external/amd/amd_preprocess.o

# target to build an object file
linsys/external/amd/amd_preprocess.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_preprocess.c.o
.PHONY : linsys/external/amd/amd_preprocess.c.o

linsys/external/amd/amd_preprocess.i: linsys/external/amd/amd_preprocess.c.i
.PHONY : linsys/external/amd/amd_preprocess.i

# target to preprocess a source file
linsys/external/amd/amd_preprocess.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_preprocess.c.i
.PHONY : linsys/external/amd/amd_preprocess.c.i

linsys/external/amd/amd_preprocess.s: linsys/external/amd/amd_preprocess.c.s
.PHONY : linsys/external/amd/amd_preprocess.s

# target to generate assembly for a file
linsys/external/amd/amd_preprocess.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_preprocess.c.s
.PHONY : linsys/external/amd/amd_preprocess.c.s

linsys/external/amd/amd_valid.o: linsys/external/amd/amd_valid.c.o
.PHONY : linsys/external/amd/amd_valid.o

# target to build an object file
linsys/external/amd/amd_valid.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_valid.c.o
.PHONY : linsys/external/amd/amd_valid.c.o

linsys/external/amd/amd_valid.i: linsys/external/amd/amd_valid.c.i
.PHONY : linsys/external/amd/amd_valid.i

# target to preprocess a source file
linsys/external/amd/amd_valid.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_valid.c.i
.PHONY : linsys/external/amd/amd_valid.c.i

linsys/external/amd/amd_valid.s: linsys/external/amd/amd_valid.c.s
.PHONY : linsys/external/amd/amd_valid.s

# target to generate assembly for a file
linsys/external/amd/amd_valid.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/amd/amd_valid.c.s
.PHONY : linsys/external/amd/amd_valid.c.s

linsys/external/qdldl/qdldl.o: linsys/external/qdldl/qdldl.c.o
.PHONY : linsys/external/qdldl/qdldl.o

# target to build an object file
linsys/external/qdldl/qdldl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/qdldl/qdldl.c.o
.PHONY : linsys/external/qdldl/qdldl.c.o

linsys/external/qdldl/qdldl.i: linsys/external/qdldl/qdldl.c.i
.PHONY : linsys/external/qdldl/qdldl.i

# target to preprocess a source file
linsys/external/qdldl/qdldl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/qdldl/qdldl.c.i
.PHONY : linsys/external/qdldl/qdldl.c.i

linsys/external/qdldl/qdldl.s: linsys/external/qdldl/qdldl.c.s
.PHONY : linsys/external/qdldl/qdldl.s

# target to generate assembly for a file
linsys/external/qdldl/qdldl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/external/qdldl/qdldl.c.s
.PHONY : linsys/external/qdldl/qdldl.c.s

linsys/mkl/direct/private.o: linsys/mkl/direct/private.c.o
.PHONY : linsys/mkl/direct/private.o

# target to build an object file
linsys/mkl/direct/private.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/linsys/mkl/direct/private.c.o
.PHONY : linsys/mkl/direct/private.c.o

linsys/mkl/direct/private.i: linsys/mkl/direct/private.c.i
.PHONY : linsys/mkl/direct/private.i

# target to preprocess a source file
linsys/mkl/direct/private.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/linsys/mkl/direct/private.c.i
.PHONY : linsys/mkl/direct/private.c.i

linsys/mkl/direct/private.s: linsys/mkl/direct/private.c.s
.PHONY : linsys/mkl/direct/private.s

# target to generate assembly for a file
linsys/mkl/direct/private.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/linsys/mkl/direct/private.c.s
.PHONY : linsys/mkl/direct/private.c.s

linsys/scs_matrix.o: linsys/scs_matrix.c.o
.PHONY : linsys/scs_matrix.o

# target to build an object file
linsys/scs_matrix.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/scs_matrix.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/linsys/scs_matrix.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/linsys/scs_matrix.c.o
.PHONY : linsys/scs_matrix.c.o

linsys/scs_matrix.i: linsys/scs_matrix.c.i
.PHONY : linsys/scs_matrix.i

# target to preprocess a source file
linsys/scs_matrix.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/scs_matrix.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/linsys/scs_matrix.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/linsys/scs_matrix.c.i
.PHONY : linsys/scs_matrix.c.i

linsys/scs_matrix.s: linsys/scs_matrix.c.s
.PHONY : linsys/scs_matrix.s

# target to generate assembly for a file
linsys/scs_matrix.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/linsys/scs_matrix.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/linsys/scs_matrix.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/linsys/scs_matrix.c.s
.PHONY : linsys/scs_matrix.c.s

src/aa.o: src/aa.c.o
.PHONY : src/aa.o

# target to build an object file
src/aa.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/aa.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/aa.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/aa.c.o
.PHONY : src/aa.c.o

src/aa.i: src/aa.c.i
.PHONY : src/aa.i

# target to preprocess a source file
src/aa.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/aa.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/aa.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/aa.c.i
.PHONY : src/aa.c.i

src/aa.s: src/aa.c.s
.PHONY : src/aa.s

# target to generate assembly for a file
src/aa.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/aa.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/aa.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/aa.c.s
.PHONY : src/aa.c.s

src/cones.o: src/cones.c.o
.PHONY : src/cones.o

# target to build an object file
src/cones.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/cones.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/cones.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/cones.c.o
.PHONY : src/cones.c.o

src/cones.i: src/cones.c.i
.PHONY : src/cones.i

# target to preprocess a source file
src/cones.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/cones.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/cones.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/cones.c.i
.PHONY : src/cones.c.i

src/cones.s: src/cones.c.s
.PHONY : src/cones.s

# target to generate assembly for a file
src/cones.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/cones.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/cones.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/cones.c.s
.PHONY : src/cones.c.s

src/ctrlc.o: src/ctrlc.c.o
.PHONY : src/ctrlc.o

# target to build an object file
src/ctrlc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/ctrlc.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/ctrlc.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/ctrlc.c.o
.PHONY : src/ctrlc.c.o

src/ctrlc.i: src/ctrlc.c.i
.PHONY : src/ctrlc.i

# target to preprocess a source file
src/ctrlc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/ctrlc.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/ctrlc.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/ctrlc.c.i
.PHONY : src/ctrlc.c.i

src/ctrlc.s: src/ctrlc.c.s
.PHONY : src/ctrlc.s

# target to generate assembly for a file
src/ctrlc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/ctrlc.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/ctrlc.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/ctrlc.c.s
.PHONY : src/ctrlc.c.s

src/exp_cone.o: src/exp_cone.c.o
.PHONY : src/exp_cone.o

# target to build an object file
src/exp_cone.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/exp_cone.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/exp_cone.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/exp_cone.c.o
.PHONY : src/exp_cone.c.o

src/exp_cone.i: src/exp_cone.c.i
.PHONY : src/exp_cone.i

# target to preprocess a source file
src/exp_cone.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/exp_cone.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/exp_cone.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/exp_cone.c.i
.PHONY : src/exp_cone.c.i

src/exp_cone.s: src/exp_cone.c.s
.PHONY : src/exp_cone.s

# target to generate assembly for a file
src/exp_cone.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/exp_cone.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/exp_cone.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/exp_cone.c.s
.PHONY : src/exp_cone.c.s

src/linalg.o: src/linalg.c.o
.PHONY : src/linalg.o

# target to build an object file
src/linalg.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/linalg.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/linalg.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/linalg.c.o
.PHONY : src/linalg.c.o

src/linalg.i: src/linalg.c.i
.PHONY : src/linalg.i

# target to preprocess a source file
src/linalg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/linalg.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/linalg.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/linalg.c.i
.PHONY : src/linalg.c.i

src/linalg.s: src/linalg.c.s
.PHONY : src/linalg.s

# target to generate assembly for a file
src/linalg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/linalg.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/linalg.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/linalg.c.s
.PHONY : src/linalg.c.s

src/normalize.o: src/normalize.c.o
.PHONY : src/normalize.o

# target to build an object file
src/normalize.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/normalize.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/normalize.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/normalize.c.o
.PHONY : src/normalize.c.o

src/normalize.i: src/normalize.c.i
.PHONY : src/normalize.i

# target to preprocess a source file
src/normalize.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/normalize.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/normalize.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/normalize.c.i
.PHONY : src/normalize.c.i

src/normalize.s: src/normalize.c.s
.PHONY : src/normalize.s

# target to generate assembly for a file
src/normalize.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/normalize.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/normalize.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/normalize.c.s
.PHONY : src/normalize.c.s

src/rw.o: src/rw.c.o
.PHONY : src/rw.o

# target to build an object file
src/rw.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/rw.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/rw.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/rw.c.o
.PHONY : src/rw.c.o

src/rw.i: src/rw.c.i
.PHONY : src/rw.i

# target to preprocess a source file
src/rw.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/rw.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/rw.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/rw.c.i
.PHONY : src/rw.c.i

src/rw.s: src/rw.c.s
.PHONY : src/rw.s

# target to generate assembly for a file
src/rw.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/rw.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/rw.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/rw.c.s
.PHONY : src/rw.c.s

src/scs.o: src/scs.c.o
.PHONY : src/scs.o

# target to build an object file
src/scs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/scs.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/scs.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/scs.c.o
.PHONY : src/scs.c.o

src/scs.i: src/scs.c.i
.PHONY : src/scs.i

# target to preprocess a source file
src/scs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/scs.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/scs.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/scs.c.i
.PHONY : src/scs.c.i

src/scs.s: src/scs.c.s
.PHONY : src/scs.s

# target to generate assembly for a file
src/scs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/scs.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/scs.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/scs.c.s
.PHONY : src/scs.c.s

src/scs_version.o: src/scs_version.c.o
.PHONY : src/scs_version.o

# target to build an object file
src/scs_version.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/scs_version.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/scs_version.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/scs_version.c.o
.PHONY : src/scs_version.c.o

src/scs_version.i: src/scs_version.c.i
.PHONY : src/scs_version.i

# target to preprocess a source file
src/scs_version.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/scs_version.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/scs_version.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/scs_version.c.i
.PHONY : src/scs_version.c.i

src/scs_version.s: src/scs_version.c.s
.PHONY : src/scs_version.s

# target to generate assembly for a file
src/scs_version.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/scs_version.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/scs_version.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/scs_version.c.s
.PHONY : src/scs_version.c.s

src/util.o: src/util.c.o
.PHONY : src/util.o

# target to build an object file
src/util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/util.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/util.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/util.c.o
.PHONY : src/util.c.o

src/util.i: src/util.c.i
.PHONY : src/util.i

# target to preprocess a source file
src/util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/util.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/util.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/util.c.i
.PHONY : src/util.c.i

src/util.s: src/util.c.s
.PHONY : src/util.s

# target to generate assembly for a file
src/util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsdir.dir/build.make CMakeFiles/scsdir.dir/src/util.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsindir.dir/build.make CMakeFiles/scsindir.dir/src/util.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scsmkl.dir/build.make CMakeFiles/scsmkl.dir/src/util.c.s
.PHONY : src/util.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... scsdir"
	@echo "... scsindir"
	@echo "... scsmkl"
	@echo "... linsys/cpu/direct/private.o"
	@echo "... linsys/cpu/direct/private.i"
	@echo "... linsys/cpu/direct/private.s"
	@echo "... linsys/cpu/indirect/private.o"
	@echo "... linsys/cpu/indirect/private.i"
	@echo "... linsys/cpu/indirect/private.s"
	@echo "... linsys/csparse.o"
	@echo "... linsys/csparse.i"
	@echo "... linsys/csparse.s"
	@echo "... linsys/external/amd/SuiteSparse_config.o"
	@echo "... linsys/external/amd/SuiteSparse_config.i"
	@echo "... linsys/external/amd/SuiteSparse_config.s"
	@echo "... linsys/external/amd/amd_1.o"
	@echo "... linsys/external/amd/amd_1.i"
	@echo "... linsys/external/amd/amd_1.s"
	@echo "... linsys/external/amd/amd_2.o"
	@echo "... linsys/external/amd/amd_2.i"
	@echo "... linsys/external/amd/amd_2.s"
	@echo "... linsys/external/amd/amd_aat.o"
	@echo "... linsys/external/amd/amd_aat.i"
	@echo "... linsys/external/amd/amd_aat.s"
	@echo "... linsys/external/amd/amd_control.o"
	@echo "... linsys/external/amd/amd_control.i"
	@echo "... linsys/external/amd/amd_control.s"
	@echo "... linsys/external/amd/amd_defaults.o"
	@echo "... linsys/external/amd/amd_defaults.i"
	@echo "... linsys/external/amd/amd_defaults.s"
	@echo "... linsys/external/amd/amd_dump.o"
	@echo "... linsys/external/amd/amd_dump.i"
	@echo "... linsys/external/amd/amd_dump.s"
	@echo "... linsys/external/amd/amd_global.o"
	@echo "... linsys/external/amd/amd_global.i"
	@echo "... linsys/external/amd/amd_global.s"
	@echo "... linsys/external/amd/amd_info.o"
	@echo "... linsys/external/amd/amd_info.i"
	@echo "... linsys/external/amd/amd_info.s"
	@echo "... linsys/external/amd/amd_order.o"
	@echo "... linsys/external/amd/amd_order.i"
	@echo "... linsys/external/amd/amd_order.s"
	@echo "... linsys/external/amd/amd_post_tree.o"
	@echo "... linsys/external/amd/amd_post_tree.i"
	@echo "... linsys/external/amd/amd_post_tree.s"
	@echo "... linsys/external/amd/amd_postorder.o"
	@echo "... linsys/external/amd/amd_postorder.i"
	@echo "... linsys/external/amd/amd_postorder.s"
	@echo "... linsys/external/amd/amd_preprocess.o"
	@echo "... linsys/external/amd/amd_preprocess.i"
	@echo "... linsys/external/amd/amd_preprocess.s"
	@echo "... linsys/external/amd/amd_valid.o"
	@echo "... linsys/external/amd/amd_valid.i"
	@echo "... linsys/external/amd/amd_valid.s"
	@echo "... linsys/external/qdldl/qdldl.o"
	@echo "... linsys/external/qdldl/qdldl.i"
	@echo "... linsys/external/qdldl/qdldl.s"
	@echo "... linsys/mkl/direct/private.o"
	@echo "... linsys/mkl/direct/private.i"
	@echo "... linsys/mkl/direct/private.s"
	@echo "... linsys/scs_matrix.o"
	@echo "... linsys/scs_matrix.i"
	@echo "... linsys/scs_matrix.s"
	@echo "... src/aa.o"
	@echo "... src/aa.i"
	@echo "... src/aa.s"
	@echo "... src/cones.o"
	@echo "... src/cones.i"
	@echo "... src/cones.s"
	@echo "... src/ctrlc.o"
	@echo "... src/ctrlc.i"
	@echo "... src/ctrlc.s"
	@echo "... src/exp_cone.o"
	@echo "... src/exp_cone.i"
	@echo "... src/exp_cone.s"
	@echo "... src/linalg.o"
	@echo "... src/linalg.i"
	@echo "... src/linalg.s"
	@echo "... src/normalize.o"
	@echo "... src/normalize.i"
	@echo "... src/normalize.s"
	@echo "... src/rw.o"
	@echo "... src/rw.i"
	@echo "... src/rw.s"
	@echo "... src/scs.o"
	@echo "... src/scs.i"
	@echo "... src/scs.s"
	@echo "... src/scs_version.o"
	@echo "... src/scs_version.i"
	@echo "... src/scs_version.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

