/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class scs_ConeProgram */

#ifndef _Included_scs_ConeProgram
#define _Included_scs_ConeProgram
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     scs_ConeProgram
 * Method:    csolve
 * Signature: (Lscs/AMatrix;[D[DLscs/Cone;Lscs/Params;Lscs/Solution;)Lscs/Solution;
 */
JNIEXPORT jobject JNICALL Java_scs_ConeProgram_csolve
  (JNIEnv *, jclass, jobject, jdoubleArray, jdoubleArray, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
