/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class scs_DirectSolver */

#ifndef _Included_scs_DirectSolver
#define _Included_scs_DirectSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     scs_DirectSolver
 * Method:    csolve
 * Signature: (Lscs/AMatrix;[D[DLscs/Cone;Lscs/Settings;Lscs/Solution;Lscs/Info;)V
 */
JNIEXPORT void JNICALL Java_scs_DirectSolver_csolve
  (JNIEnv *, jclass, jobject, jdoubleArray, jdoubleArray, jobject, jobject, jobject, jobject);

/*
 * Class:     scs_DirectSolver
 * Method:    cversion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_scs_DirectSolver_cversion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
