/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class scs_IndirectSolver */

#ifndef _Included_scs_IndirectSolver
#define _Included_scs_IndirectSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     scs_IndirectSolver
 * Method:    csolve
 * Signature: (Lscs/AMatrix;[D[DLscs/Cone;Lscs/Settings;Lscs/Solution;Lscs/Info;)V
 */
JNIEXPORT void JNICALL Java_scs_IndirectSolver_csolve
  (JNIEnv *, jclass, jobject, jdoubleArray, jdoubleArray, jobject, jobject, jobject, jobject);

/*
 * Class:     scs_IndirectSolver
 * Method:    cversion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_scs_IndirectSolver_cversion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
