/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class scs_IndirectSolver */

#ifndef _Included_scs_IndirectSolver
#define _Included_scs_IndirectSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     scs_IndirectSolver
 * Method:    csolve
 * Signature: (Lscs/AMatrix;[D[DLscs/Cone;Lscs/Params;Lscs/Solution;)Lscs/Solution;
 */
JNIEXPORT jobject JNICALL Java_scs_IndirectSolver_csolve
  (JNIEnv *, jclass, jobject, jdoubleArray, jdoubleArray, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
