/*
 * GENERATED BY CMAKE
 */

/*
 * Definitions of primitive types used in SCS.
 */

#ifndef SCS_TYPES_H_GUARD
#define SCS_TYPES_H_GUARD

#ifdef __cplusplus
extern "C" {
#endif

typedef int    scs_int;
typedef double  scs_float;

#ifdef __cplusplus
}
#endif
#endif
