---
name: CMake OpenMP

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get install libopenblas-dev liblapack-dev
          mkdir out
          export INSTALL_DIR=$PWD/out
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$INSTALL_DIR/lib
          mkdir build
          cd build
          cmake -DUSE_OPENMP=ON -DBUILD_TESTING=ON -DCMAKE_INSTALL_PREFIX:PATH=$INSTALL_DIR ..
          make
          make install
          ctest --output-on-failure
          cd ../docs/src/examples/
          gcc -I$INSTALL_DIR/include/scs -L$INSTALL_DIR/lib/ qp.c -o qp.out -lscsdir
          ./qp.out

